services:
  goodface-fronted:
    image: registry.cn-hangzhou.aliyuncs.com/library/nginx:1.25-alpine
    container_name: goodface-fronted
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro