services:
  goodface-fronted:
    image: nginx:1.25-alpine
    container_name: goodface-fronted
    restart: always
    ports:
      - "${FRONT_HTTP_PORT:-8080}:80"
      - "${FRONT_HTTPS_PORT:-8443}:443"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro